version: "3.4"
services:
  dozzle:
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_FILTER=name=dozzle
    build:
      context: ..   
      dockerfile: Dockerfile.self-contained
  integration:
    build:
      context: .
    command: npm test
    environment:
      - BASE=http://dozzle:8080/
    depends_on:
      - dozzle
