on: push
name: Test
jobs:
  npm-test:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Install depdencies
        run: yarn
      - name: Run Tests
        run: yarn test
  go-test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Go Tests with Coverage
        run: go test -cover ./...
  int-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build images
        run: docker-compose -f integration/docker-compose.test.yml build
      - name: Run tests
        run: docker-compose -f integration/docker-compose.test.yml run integration
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Install packr
        run: go install github.com/gobuffalo/packr/packr
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Install npm depdencies
        run: yarn
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --snapshot --skip-publish --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
